language: go

go:
  - "1.11"

notifications:
  email: false

script:
  - go test ./...
  - GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Commit=${TRAVIS_COMMIT} -X main.Build=$(date +%Y%m%d) -s -w" -o pathfinder-agent-linux
  - GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.Commit=${TRAVIS_COMMIT} -X main.Build=$(date +%Y%m%d) -s -w" -o pathfinder-agent-darwin

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - pathfinder-agent-linux
    - pathfinder-agent-darwin
  on:
    tags: true
    repo: pathfinder-cm/pathfinder-agent
    all_branches: true
